import React from 'react'
import { useGLTF } from '@react-three/drei'
import { ThreeElements } from '@react-three/fiber'
import { Mesh, Material, BufferGeometry } from 'three'

type GLTFModel = {
  nodes: Record<string, Mesh & { geometry: BufferGeometry }>
  materials: Record<string, Material>
}

export function Model(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/assets/model/ImageToStl.com_BFM+Icon+White.gltf') as unknown as GLTFModel

  return (
    <group {...props} dispose={null}>
      <mesh
        name="Node2"
        castShadow
        receiveShadow
        geometry={nodes.Node2.geometry}
        material={materials['#720000']}
      />
      <mesh
        name="Mesh0"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0.geometry}
        material={materials['#720000']}
      />
      <mesh
        name="Mesh0_1"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_1.geometry}
        material={materials['#7A0000']}
      />
      <mesh
        name="Mesh0_2"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_2.geometry}
        material={materials['#840000']}
      />
      <mesh
        name="Mesh0_3"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_3.geometry}
        material={materials['#830000']}
      />
      <mesh
        name="Mesh0_4"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_4.geometry}
        material={materials['#800000']}
      />
      <mesh
        name="Mesh0_5"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_5.geometry}
        material={materials['#660000']}
      />
      <mesh
        name="Mesh0_6"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_6.geometry}
        material={materials['#5D0000']}
      />
      <mesh
        name="Mesh0_7"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_7.geometry}
        material={materials['#8A0000']}
      />
      <mesh
        name="Mesh0_8"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_8.geometry}
        material={materials['#790000']}
      />
      <mesh
        name="Mesh0_9"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_9.geometry}
        material={materials['#770000']}
      />
      <mesh
        name="Mesh0_10"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_10.geometry}
        material={materials['#810000']}
      />
      <mesh
        name="Mesh0_11"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_11.geometry}
        material={materials['#780000']}
      />
      <mesh
        name="Mesh0_12"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_12.geometry}
        material={materials['#6C0000']}
      />
      <mesh
        name="Mesh0_13"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_13.geometry}
        material={materials['#690000']}
      />
      <mesh
        name="Mesh0_14"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_14.geometry}
        material={materials['#460000']}
      />
      <mesh
        name="Mesh0_15"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_15.geometry}
        material={materials['#570000']}
      />
      <mesh
        name="Mesh0_16"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_16.geometry}
        material={materials['#5F0000']}
      />
      <mesh
        name="Mesh0_17"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_17.geometry}
        material={materials['#880000']}
      />
      <mesh
        name="Mesh0_18"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_18.geometry}
        material={materials['#870000']}
      />
      <mesh
        name="Mesh0_19"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_19.geometry}
        material={materials['#860000']}
      />
      <mesh
        name="Mesh0_20"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_20.geometry}
        material={materials['#750000']}
      />
      <mesh
        name="Mesh0_21"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_21.geometry}
        material={materials['#700000']}
      />
      <mesh
        name="Mesh0_22"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_22.geometry}
        material={materials['#6D0000']}
      />
      <mesh
        name="Mesh0_23"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_23.geometry}
        material={materials['#6E0000']}
      />
      <mesh
        name="Mesh0_24"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_24.geometry}
        material={materials['#7D0000']}
      />
      <mesh
        name="Mesh0_25"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_25.geometry}
        material={materials['#730000']}
      />
      <mesh
        name="Mesh0_26"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_26.geometry}
        material={materials['#740000']}
      />
      <mesh
        name="Mesh0_27"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_27.geometry}
        material={materials['#540000']}
      />
      <mesh
        name="Mesh0_28"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_28.geometry}
        material={materials['#5A0000']}
      />
      <mesh
        name="Mesh0_29"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_29.geometry}
        material={materials['#650000']}
      />
      <mesh
        name="Mesh0_30"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_30.geometry}
        material={materials['#6A0000']}
      />
      <mesh
        name="Mesh0_31"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_31.geometry}
        material={materials['#2D0000']}
      />
      <mesh
        name="Mesh0_32"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_32.geometry}
        material={materials['#440000']}
      />
      <mesh
        name="Mesh0_33"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_33.geometry}
        material={materials['#500000']}
      />
      <mesh
        name="Mesh0_34"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_34.geometry}
        material={materials['#6B0000']}
      />
      <mesh
        name="Mesh0_35"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_35.geometry}
        material={materials['#8C0000']}
      />
      <mesh
        name="Mesh0_36"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_36.geometry}
        material={materials['#850000']}
      />
      <mesh
        name="Mesh0_37"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_37.geometry}
        material={materials['#7C0000']}
      />
      <mesh
        name="Mesh0_38"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_38.geometry}
        material={materials['#7F0000']}
      />
      <mesh
        name="Mesh0_39"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_39.geometry}
        material={materials['#6F0000']}
      />
      <mesh
        name="Mesh0_40"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_40.geometry}
        material={materials['#5B0000']}
      />
      <mesh
        name="Mesh0_41"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_41.geometry}
        material={materials['#2F0000']}
      />
      <mesh
        name="Mesh0_42"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_42.geometry}
        material={materials['#520000']}
      />
      <mesh
        name="Mesh0_43"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_43.geometry}
        material={materials['#8B0000']}
      />
      <mesh
        name="Mesh0_44"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_44.geometry}
        material={materials['#600000']}
      />
      <mesh
        name="Mesh0_45"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_45.geometry}
        material={materials['#7B0000']}
      />
      <mesh
        name="Mesh0_46"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_46.geometry}
        material={materials['#5E0000']}
      />
      <mesh
        name="Mesh0_47"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_47.geometry}
        material={materials['#610000']}
      />
      <mesh
        name="Mesh0_48"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_48.geometry}
        material={materials['#670000']}
      />
      <mesh
        name="Mesh0_49"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_49.geometry}
        material={materials['#710000']}
      />
      <mesh
        name="Mesh0_50"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_50.geometry}
        material={materials['#590000']}
      />
      <mesh
        name="Mesh0_51"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_51.geometry}
        material={materials['#7E0000']}
      />
      <mesh
        name="Mesh0_52"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_52.geometry}
        material={materials['#760000']}
      />
      <mesh
        name="Mesh0_53"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_53.geometry}
        material={materials['#550000']}
      />
      <mesh
        name="Mesh0_54"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_54.geometry}
        material={materials['#820000']}
      />
      <mesh
        name="Mesh0_55"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_55.geometry}
        material={materials['#680000']}
      />
      <mesh
        name="Mesh0_56"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_56.geometry}
        material={materials['#410000']}
      />
      <mesh
        name="Mesh0_57"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_57.geometry}
        material={materials['#430000']}
      />
      <mesh
        name="Mesh0_58"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_58.geometry}
        material={materials['#640000']}
      />
      <mesh
        name="Mesh0_59"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_59.geometry}
        material={materials['#620000']}
      />
      <mesh
        name="Mesh0_60"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_60.geometry}
        material={materials['#930000']}
      />
      <mesh
        name="Mesh0_61"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_61.geometry}
        material={materials['#8D0000']}
      />
      <mesh
        name="Mesh0_62"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_62.geometry}
        material={materials['#630000']}
      />
      <mesh
        name="Mesh0_63"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_63.geometry}
        material={materials['#4C0000']}
      />
      <mesh
        name="Mesh0_64"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_64.geometry}
        material={materials['#8E0000']}
      />
      <mesh
        name="Mesh0_65"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_65.geometry}
        material={materials['#5C0000']}
      />
      <mesh
        name="Mesh0_66"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_66.geometry}
        material={materials['#530000']}
      />
      <mesh
        name="Mesh0_67"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_67.geometry}
        material={materials['#580000']}
      />
      <mesh
        name="Mesh0_68"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_68.geometry}
        material={materials['#900000']}
      />
      <mesh
        name="Mesh0_69"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_69.geometry}
        material={materials['#890000']}
      />
      <mesh
        name="Mesh0_70"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_70.geometry}
        material={materials['#8F0000']}
      />
      <mesh
        name="Mesh0_71"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_71.geometry}
        material={materials['#910000']}
      />
      <mesh
        name="Mesh0_72"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_72.geometry}
        material={materials['#490000']}
      />
      <mesh
        name="Mesh0_73"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_73.geometry}
        material={materials['#4D0000']}
      />
      <mesh
        name="Mesh0_74"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_74.geometry}
        material={materials['#270000']}
      />
      <mesh
        name="Mesh0_75"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_75.geometry}
        material={materials['#2C0000']}
      />
      <mesh
        name="Mesh0_76"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_76.geometry}
        material={materials['#000000']}
      />
      <mesh
        name="Mesh0_77"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_77.geometry}
        material={materials['#1D0000']}
      />
      <mesh
        name="Mesh0_78"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_78.geometry}
        material={materials['#220000']}
      />
      <mesh
        name="Mesh0_79"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_79.geometry}
        material={materials['#920000']}
      />
      <mesh
        name="Mesh0_80"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_80.geometry}
        material={materials['#560000']}
      />
      <mesh
        name="Mesh0_81"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_81.geometry}
        material={materials['#980000']}
      />
      <mesh
        name="Mesh0_82"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_82.geometry}
        material={materials['#970000']}
      />
      <mesh
        name="Mesh0_83"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_83.geometry}
        material={materials['#190000']}
      />
      <mesh
        name="Mesh0_84"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_84.geometry}
        material={materials['#4A0000']}
      />
      <mesh
        name="Mesh0_85"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_85.geometry}
        material={materials['#040000']}
      />
      <mesh
        name="Mesh0_86"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_86.geometry}
        material={materials['#060000']}
      />
      <mesh
        name="Mesh0_87"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_87.geometry}
        material={materials['#3E0000']}
      />
      <mesh
        name="Mesh0_88"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_88.geometry}
        material={materials['#380000']}
      />
      <mesh
        name="Mesh0_89"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_89.geometry}
        material={materials['#940000']}
      />
      <mesh
        name="Mesh0_90"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_90.geometry}
        material={materials['#020000']}
      />
      <mesh
        name="Mesh0_91"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_91.geometry}
        material={materials['#370000']}
      />
      <mesh
        name="Mesh0_92"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_92.geometry}
        material={materials['#310000']}
      />
      <mesh
        name="Mesh0_93"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_93.geometry}
        material={materials['#350000']}
      />
      <mesh
        name="Mesh0_94"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_94.geometry}
        material={materials['#390000']}
      />
      <mesh
        name="Mesh0_95"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_95.geometry}
        material={materials['#450000']}
      />
      <mesh
        name="Mesh0_96"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_96.geometry}
        material={materials['#320000']}
      />
      <mesh
        name="Mesh0_97"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_97.geometry}
        material={materials['#2A0000']}
      />
      <mesh
        name="Mesh0_98"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_98.geometry}
        material={materials['#3D0000']}
      />
      <mesh
        name="Mesh0_99"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_99.geometry}
        material={materials['#400000']}
      />
      <mesh
        name="Mesh0_100"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_100.geometry}
        material={materials['#950000']}
      />
      <mesh
        name="Mesh0_101"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_101.geometry}
        material={materials['#300000']}
      />
      <mesh
        name="Mesh0_102"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_102.geometry}
        material={materials['#470000']}
      />
      <mesh
        name="Mesh0_103"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_103.geometry}
        material={materials['#420000']}
      />
      <mesh
        name="Mesh0_104"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_104.geometry}
        material={materials['#3F0000']}
      />
      <mesh
        name="Mesh0_105"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_105.geometry}
        material={materials['#480000']}
      />
      <mesh
        name="Mesh0_106"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_106.geometry}
        material={materials['#210000']}
      />
      <mesh
        name="Mesh0_107"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_107.geometry}
        material={materials['#4E0000']}
      />
      <mesh
        name="Mesh0_108"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_108.geometry}
        material={materials['#4F0000']}
      />
      <mesh
        name="Mesh0_109"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_109.geometry}
        material={materials['#3C0000']}
      />
      <mesh
        name="Mesh0_110"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_110.geometry}
        material={materials['#3A0000']}
      />
      <mesh
        name="Mesh0_111"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_111.geometry}
        material={materials['#1B0000']}
      />
      <mesh
        name="Mesh0_112"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_112.geometry}
        material={materials['#240000']}
      />
      <mesh
        name="Mesh0_113"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_113.geometry}
        material={materials['#9D0000']}
      />
      <mesh
        name="Mesh0_114"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_114.geometry}
        material={materials['#100000']}
      />
      <mesh
        name="Mesh0_115"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_115.geometry}
        material={materials['#510000']}
      />
      <mesh
        name="Mesh0_116"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_116.geometry}
        material={materials['#9B0000']}
      />
      <mesh
        name="Mesh0_117"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_117.geometry}
        material={materials['#0C0000']}
      />
      <mesh
        name="Mesh0_118"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_118.geometry}
        material={materials['#4B0000']}
      />
      <mesh
        name="Mesh0_119"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_119.geometry}
        material={materials['#9A0000']}
      />
      <mesh
        name="Mesh0_120"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_120.geometry}
        material={materials['#070000']}
      />
      <mesh
        name="Mesh0_121"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_121.geometry}
        material={materials['#3B0000']}
      />
      <mesh
        name="Mesh0_122"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_122.geometry}
        material={materials['#990000']}
      />
      <mesh
        name="Mesh0_123"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_123.geometry}
        material={materials['#A00000']}
      />
      <mesh
        name="Mesh0_124"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_124.geometry}
        material={materials['#050000']}
      />
      <mesh
        name="Mesh0_125"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_125.geometry}
        material={materials['#9C0000']}
      />
      <mesh
        name="Mesh0_126"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_126.geometry}
        material={materials['#280000']}
      />
      <mesh
        name="Mesh0_127"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_127.geometry}
        material={materials['#330000']}
      />
      <mesh
        name="Mesh0_128"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_128.geometry}
        material={materials['#340000']}
      />
      <mesh
        name="Mesh0_129"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_129.geometry}
        material={materials['#960000']}
      />
      <mesh
        name="Mesh0_130"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_130.geometry}
        material={materials['#200000']}
      />
      <mesh
        name="Mesh0_131"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_131.geometry}
        material={materials['#1A0000']}
      />
      <mesh
        name="Mesh0_132"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_132.geometry}
        material={materials['#0E0000']}
      />
      <mesh
        name="Mesh0_133"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_133.geometry}
        material={materials['#9F0000']}
      />
      <mesh
        name="Mesh0_134"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_134.geometry}
        material={materials['#9E0000']}
      />
      <mesh
        name="Mesh0_135"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_135.geometry}
        material={materials['#1C0000']}
      />
      <mesh
        name="Mesh0_136"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_136.geometry}
        material={materials['#A30000']}
      />
      <mesh
        name="Mesh0_137"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_137.geometry}
        material={materials['#160000']}
      />
      <mesh
        name="Mesh0_138"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_138.geometry}
        material={materials['#A10000']}
      />
      <mesh
        name="Mesh0_139"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_139.geometry}
        material={materials['#0D0000']}
      />
      <mesh
        name="Mesh0_140"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_140.geometry}
        material={materials['#0B0000']}
      />
      <mesh
        name="Mesh0_141"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_141.geometry}
        material={materials['#110000']}
      />
      <mesh
        name="Mesh0_142"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_142.geometry}
        material={materials['#360000']}
      />
      <mesh
        name="Mesh0_143"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_143.geometry}
        material={materials['#A60000']}
      />
      <mesh
        name="Mesh0_144"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_144.geometry}
        material={materials['#A20000']}
      />
      <mesh
        name="Mesh0_145"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_145.geometry}
        material={materials['#A80000']}
      />
      <mesh
        name="Mesh0_146"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_146.geometry}
        material={materials['#A70000']}
      />
      <mesh
        name="Mesh0_147"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_147.geometry}
        material={materials['#A40000']}
      />
      <mesh
        name="Mesh0_148"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_148.geometry}
        material={materials['#A50000']}
      />
      <mesh
        name="Mesh0_149"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_149.geometry}
        material={materials['#AA0000']}
      />
      <mesh
        name="Mesh0_150"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_150.geometry}
        material={materials['#A90000']}
      />
      <mesh
        name="Mesh0_151"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_151.geometry}
        material={materials['#180000']}
      />
      <mesh
        name="Mesh0_152"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_152.geometry}
        material={materials['#260000']}
      />
      <mesh
        name="Mesh0_153"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_153.geometry}
        material={materials['#2B0000']}
      />
      <mesh
        name="Mesh0_154"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_154.geometry}
        material={materials['#1E0000']}
      />
      <mesh
        name="Mesh0_155"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_155.geometry}
        material={materials['#130000']}
      />
      <mesh
        name="Mesh0_156"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_156.geometry}
        material={materials['#2E0000']}
      />
      <mesh
        name="Mesh0_157"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_157.geometry}
        material={materials['#0F0000']}
      />
      <mesh
        name="Mesh0_158"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_158.geometry}
        material={materials['#250000']}
      />
      <mesh
        name="Mesh0_159"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_159.geometry}
        material={materials['#090000']}
      />
      <mesh
        name="Mesh0_160"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_160.geometry}
        material={materials['#080000']}
      />
      <mesh
        name="Mesh0_161"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_161.geometry}
        material={materials['#1F0000']}
      />
      <mesh
        name="Mesh0_162"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_162.geometry}
        material={materials['#230000']}
      />
      <mesh
        name="Mesh0_163"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_163.geometry}
        material={materials['#150000']}
      />
      <mesh
        name="Mesh0_164"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_164.geometry}
        material={materials['#120000']}
      />
      <mesh
        name="Mesh0_165"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_165.geometry}
        material={materials['#FFFFFF']}
      />
      <mesh
        name="Mesh0_166"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_166.geometry}
        material={materials['#170000']}
      />
      <mesh
        name="Mesh0_167"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_167.geometry}
        material={materials['#290000']}
      />
      <mesh
        name="Mesh0_168"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_168.geometry}
        material={materials['#AC0000']}
      />
      <mesh
        name="Mesh0_169"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_169.geometry}
        material={materials['#140000']}
      />
      <mesh
        name="Mesh0_170"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_170.geometry}
        material={materials['#AB0000']}
      />
      <mesh
        name="Mesh0_171"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_171.geometry}
        material={materials['#0A0000']}
      />
      <mesh
        name="Mesh0_172"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_172.geometry}
        material={materials['#030000']}
      />
      <mesh
        name="Mesh0_173"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_173.geometry}
        material={materials['#B20000']}
      />
      <mesh
        name="Mesh0_174"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_174.geometry}
        material={materials['#AE0000']}
      />
      <mesh
        name="Mesh0_175"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_175.geometry}
        material={materials['#AD0000']}
      />
      <mesh
        name="Mesh0_176"
        castShadow
        receiveShadow
        geometry={nodes.Mesh0_176.geometry}
        material={materials['#B10000']}
      />
    </group>
  )
}

useGLTF.preload('/assets/model/ImageToStl.com_BFM+Icon+White.gltf')